# Generated by Django 4.2.7 on 2024-05-07 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название задания')),
                ('description', models.CharField(max_length=600, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='image_todo/', verbose_name='Фотография')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Статус выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата задания')),
                ('performing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Выполняющий таск')),
            ],
            options={
                'verbose_name': 'Список задач',
                'verbose_name_plural': 'Списки задач',
            },
        ),
    ]
